# see https://github.com/sigoden/aichat/blob/main/config.example.yaml

model: openai:gpt-5.2
clients:
- type: openai
  patch:
    chat_completions:
      'gpt-5\.6-luna.*':
        body:
          reasoning_effort: low
- type: claude
