-- < https://github.com/ChristianChiarulli/nvim/blob/master/lua/user/icons.lua >
-- < https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/init.lua >
-- < https://github.com/microsoft/vscode/blob/main/src/vs/base/common/codicons.ts >

-- go to the above and then enter <c-v>u<unicode> and the symbold should appear
-- or go here and upload the font file: https://mathew-kurian.github.io/CharacterMap/
-- find more here: https://www.nerdfonts.com/cheat-sheet

return {
  dap = {
    Stopped = { "󰁕 ", "DiagnosticWarn", "DapStoppedLine" },
    Breakpoint = " ",
    BreakpointCondition = " ",
    BreakpointRejected = { " ", "DiagnosticError" },
    LogPoint = ".>",
  },
  documents = {
    File = " ",
    Files = " ",
    Folder = " ",
    OpenFolder = " ",
  },
  git = {
    added = " ",
    modified = " ",
    removed = " ",
    ignored = "◌",
    unstaged  = "󰄗 ",
    untracked = "",
    staged    = "",
    deleted   = "✘ ",
    renamed = " ",
    conflict  = "",
    diff = " ",
    repo = " ",
  },
  kinds = {
    Array = " ",
    Boolean = " ",
    Class = " ",
    Color = " ",
    Constant = " ",
    Constructor = " ",
    Copilot = " ",
    Enum = " ",
    EnumMember = " ",
    Event = " ",
    Field = " ",
    File = " ",
    Folder = " ",
    Function = " ",
    Interface = " ",
    Key = " ",
    Keyword = " ",
    Method = " ",
    Module = " ",
    Namespace = " ",
    Null = " ",
    Number = " ",
    Object = " ",
    Operator = " ",
    Package = " ",
    Property = " ",
    Reference = " ",
    Snippet = " ",
    String = " ",
    Struct = " ",
    Text = " ",
    TypeParameter = " ",
    Unit = " ",
    Value = " ",
    Variable = " ",
  },
  type = {
    Array = "󰅨 ",
    Number = " ",
    String = " ",
    Boolean = " ",
    Object = " ",
  },
  ui = {
    ArrowClosed = " ",
    ArrowOpen = " ",
    Lock = "",
    Circle = " ",
    BigCircle = " ",
    BigUnfilledCircle = " ",
    Close = "",
    NewFile = " ",
    Search = " ",
    Lightbulb = "󱉵",
    Project = " ",
    Dashboard = " ",
    History = " ",
    Comment = " ",
    Bug = " ",
    Code = "",
    Telescope = " ",
    Gear = " ",
    Package = " ",
    List = "",
    SignIn = " ",
    SignOut = " ",
    Check = " ",
    Fire = " ",
    Note = " ",
    BookMark = " ",
    Pencil = "󰙏 ",
    ChevronRight = "",
    Table = " ",
    Calendar = " ",
    CloudDownload = " ",
  },
  diagnostics = {
    Error = " ",
    Warn = " ",
    Hint = " ",
    Info = " ",
    -- Error = " ",
    -- Warn = " ",
    -- Hint = " ",
    -- Info = " ",
    Question = " ",
  },
  misc = {
    Robot = "󱚤 ",
    Squirrel = " ",
    Tag = " ",
    Watch = " ",
    Smiley = " ",
    Package = " ",
    CircuitBoard = " ",
  },
}
