# everforest_dark_medium: &everforest_dark_medium
# https://gist.github.com/leoluyi/d07a138f65ebd99b48f0fc8125b9b58b

[colors.primary]
background = "#272e33"
foreground = "#d3c6aa"

[colors.normal]
black = "#414b50"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"

[colors.bright]
black = "#475258"
blue = "#7fbbb3"
cyan = "#83c092"
green = "#a7c080"
magenta = "#d699b6"
red = "#e67e80"
white = "#d3c6aa"
yellow = "#dbbc7f"
